# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inMhGD70p-dC6QHOtgacLQ9kUnBnkgIJ
"""

# Phase-2 Data Science Project - AQI Analysis

# Step 1: Import Required Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Load the Dataset
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('aqi_data.csv')  # Replace with actual filename after upload

# Step 3: View Dataset Info
print("Dataset Shape:", df.shape)
print("\nFirst 5 rows:\n", df.head())
print("\nStatistical Summary:\n", df.describe())
print("\nNull Values:\n", df.isnull().sum())

# Step 4: Data Preprocessing
# Convert monthly columns to numeric
month_columns = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
df[month_columns] = df[month_columns].apply(pd.to_numeric, errors='coerce')

# Step 5: Visualization - Monthly AQI Trend
monthly_avg = df[month_columns].mean()

plt.figure(figsize=(10, 6))
sns.lineplot(x=month_columns, y=monthly_avg.values, marker='o')
plt.title('Average AQI by Month')
plt.xlabel('Month')
plt.ylabel('Average AQI')
plt.grid(True)
plt.show()

# Step 6: Visualization - Top 10 Polluted Cities
top10 = df[['city', 'avg']].sort_values(by='avg', ascending=False).head(10)

plt.figure(figsize=(12, 6))
sns.barplot(data=top10, x='avg', y='city', palette='Reds_r')
plt.title('Top 10 Polluted Cities by Average AQI')
plt.xlabel('Average AQI')
plt.ylabel('City')
plt.show()

# Step 7: Conclusion
print("\nConclusion:")
print("1. AQI is highest in winter months (Jan, Nov, Dec).")
print("2. Cities like Begusarai, Patna, and Saharsa have very high pollution levels.")